task: validation

data:
  batch_size: 16
  image_size: ${image_size}
  cpu_num: ${cpu_num}
  shuffle: False
  pin_memory: True
  data_augment: {}
  dynamic_shape: False

nms:
  min_confidence: 0.01  # Increased to reduce false positives
  min_iou: 0.4  # Adjusted to balance precision/recall
  max_bbox: 500  # Reduced from 1000 to avoid unnecessary processing